### ISSUE TITLE
The GenerateTestReport.py doesn't work when just have one round fio test rusult

### ISSUE THREAD

**Issue by dulili** [SCHEN2015/virt-perf-scripts#1]
if we just run one round fio test, then run the generate test report script, there is error message.
```
[root@bootp-73-199-100 tmp]# ./GenerateTestReport.py 
  File "./GenerateTestReport.py", line 49
    for key, value in inputs.iteritems()
      ^
SyntaxError: invalid syntax
[root@bootp-73-199-100 tmp]# 
```
please check the reason.
Thanks
ldu

**Comment by SCHEN2015** [comment]
Relate code:
```python
            if isinstance(inputs, dict):
                return { byteify(key): byteify(value) for key, value in inputs.iteritems() }
```

This syntax is supported from python 2.7; to increase the compatibility I can modify the code as:
```python
            if isinstance(inputs, dict):
                #return { byteify(key): byteify(value) for key, value in inputs.iteritems() }
                for key, value in inputs.iteritems():
                        return { byteify(key): byteify(value) }
```

However, I strongly recommend you to upgrade your python version. :)

**Comment by dulili** [comment]
Hi Chenshi,
Got it, I have copy the result to my Fedora, then run with this script, it indeed works well, thanks for your quick update!
So close this issue as the problem had resolved.
