### ISSUE TITLE
[ERROR] Error while extracting performance KPIs: 'jobs'

### ISSUE THREAD

**Issue by dulili** [SCHEN2015/virt-perf-scripts#13]
when run ./GenerateTestReport.py --result_path $path
there is error [ERROR] Error while extracting performance KPIs: 'jobs'

**Comment by SCHEN2015** [comment]
Have you verified my change on RHEL7.6?

**Comment by dulili** [comment]
not yet, I will try it this weekend, thanks for reminder!

-- 
Best Regards

Lili Du

IRC:ldu@#eng-china,#virt
Tel:18518098655



----- Original Message -----

**Comment by SCHEN2015** [comment]
This issue may be caused by new packages for Python 3. I have undone the string converting to fix this problem. If you encounter any more problem, please reopen this issue.
