### ISSUE TITLE
Document Refinement about introduction

### ISSUE THREAD

**Issue by lixuemin2016** [SCHEN2015/virt-perf-scripts#17]
Following list some suggestion about documents:

    1. fio document added suggestion:

    how many cpu needed? memory needed for seting up vm

    2. Default parameter explanation, e.g runtime 1 minute, size =512M

    3. Typical scenario 
    不同场景的测试公式基本一致，只有3个参数（读写模式，iodepth，blocksize）的区别。下面举例说明使用block size为4k，iodepth为1来测试顺序读性能的命令。
    FIO： https://blog.csdn.net/qq_36357820/article/details/79965014
    block=4k iodepth=1 随机读测试，能反映磁盘的时延性能；
    block=128K iodepth=32 能反映峰值吞吐性能 ;
    block=4k iodepth=32 能反映峰值IOPS性能
4. Some parameter suggestions?
    read
        Sequential reads.
    write
        Sequential writes.
    rw,readwrite
        Sequential mixed reads and writes.

    randread
        Random reads.
    randwrite
        Random writes.
    read, write, rw -- numberjobs better 1
    randread, readwrite, rw, -- numberjobs better 16.

**Comment by SCHEN2015** [comment]
It seems like you are talking about the best practice things.
We can just tell the best practice when we base on a specific scenario. That means you may get totally different suggestions to run the fio case in different situations. My suggestion is to add the `best_practice.md` and tell some stories about general scenarios.
