### ISSUE TITLE
Change size to parameter for fio test

### ISSUE THREAD

**Issue by HuijingHei** [SCHEN2015/virt-perf-scripts#25]
Could you help to change size to parameter for fio test?

**Comment by SCHEN2015** [comment]
Sure, I'm working on that.

**Comment by SCHEN2015** [comment]
Please try this feature in devel branch.

**Comment by HuijingHei** [comment]
Hi, the 'size' parameter works well, thanks!

**Comment by SCHEN2015** [comment]
Thanks! Rebased to the master branch.
