### ISSUE TITLE
GenerateTestReport.py: Error while parsing disk_util: length != 1

### ISSUE THREAD

**Issue by lixuemin2016** [SCHEN2015/virt-perf-scripts#3]
$ GenerateTestReport.py ./rhel75_830 rhel75_830_fio_report.csv
Error while parsing disk_util: length != 1
Error while parsing disk_util: length != 1
Error while parsing disk_util: length != 1
Error while parsing disk_util: length != 1
Error while parsing disk_util: length != 1
......
Error while parsing disk_util: length != 1
Error while parsing disk_util: length != 1
Dumping data into csv file "rhel75_830_fio_report.csv"...
Finished!
$

**Comment by SCHEN2015** [comment]
In your source data `gen1_SCSI_fs_write_16k_1_mnt2tmp_4.fiolog` we can see there is an dm device. In current test scope, we don't test against any dm device. So I recognized it as an error and you would be tested against a wrong device.

```
Disk stats (read/write):
    dm-0: ios=0/3674635, merge=0/0, ticks=0/862660, in_queue=865638, util=100.00%, aggrios=0/3681579, aggrmerge=0/1, aggrticks=0/867655, aggrin_queue=867227, aggrutil=99.85%
    sda: ios=0/3681579, merge=0/1, ticks=0/867655, in_queue=867227, util=99.85%
```
