### ISSUE TITLE
[Errno 2] No such file or directory: './virt_perf_scripts.yaml'

### ISSUE THREAD

**Issue by dulili** [SCHEN2015/virt-perf-scripts#7]
Hi shichen,
when I try to run  on RHEL by default,there is a error can not found yaml file, the yaml file is on upper folder.
could you help define the path?

./RunFioTest.py 
[WARNING] Fail to get default value from yaml file. [Errno 2] No such file or directory: './virt_perf_scripts.yaml'

**Comment by SCHEN2015** [comment]
The best way to use this tool is to follow the README.md to deliver `*.py` and `*.yaml` to the VM. If you'd like to use this tool in the repo, I can add a softlink which points to `../virt_perf_scripts.yaml` for you.
