### ISSUE TITLE
Got unexpected extra argument  error when run on RHEL

### ISSUE THREAD

**Issue by dulili** [SCHEN2015/virt-perf-scripts#8]
[root@bootp-73-199-203 block]# ./RunFioTest.py  --backend NVME --driver SCSI --fs RAW --filename /dev/sdb --log_path /root--rounds 1
Usage: RunFioTest.py [OPTIONS]

Error: Got unexpected extra argument (1)

**Comment by dulili** [comment]
after check, this is not a bug.

**Comment by SCHEN2015** [comment]
Please add a blank before `--rounds`
